name: model
description: A starting point for Dart libraries or applications.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  http: ^0.12.0
  rxdart: ^0.23.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
